defaults: &defaults
  adapter:  postgresql
  encoding: unicode
  pool: 5

development:
  <<: *defaults
  database: grndz_app_development

test:
  <<: *defaults
  database: grdnz_app_test

stage:
  <<: *defaults
  database: grndz_app_development
